run-component: use dedicated mongodb-pod

diff --git a/run-component b/run-component
--- a/run-component
+++ b/run-component
@@ -19,14 +19,33 @@ then
   COLOR_PREFIX=c
 fi
 
-sed -i "s/stargazer/robot-${COLOR_PREFIX}1/g;s/orinoco/robot-${COLOR_PREFIX}2/g;s/agamemnon/robot-${COLOR_PREFIX}3/g" $FAWKES_DIR/cfg/conf.d/robot-memory.yaml
-sed -i "s/replica-set-members:.*/replica-set-members: \['fawkes-planner-${TEAM_COLOR,,}:27021','robot-${COLOR_PREFIX}1:27021','robot-${COLOR_PREFIX}2:27021','robot-${COLOR_PREFIX}3:27021'\]/g" $FAWKES_DIR/cfg/conf.d/robot-memory.yaml
-sed -i "s/hosts:/hosts:\n        fawkes-planner-${TEAM_COLOR,,}: fawkes-planner-${TEAM_COLOR,,}:27021/g" $FAWKES_DIR/cfg/conf.d/robot-memory.yaml
+sed -i "s/stargazer/mongodb-${COLOR_PREFIX}1/g;s/orinoco/mongodb-${COLOR_PREFIX}2/g;s/agamemnon/mongodb-${COLOR_PREFIX}3/g" $FAWKES_DIR/cfg/conf.d/robot-memory.yaml
+sed -i "s/replica-set-members:.*/replica-set-members: \['mongodb-planner-${TEAM_COLOR,,}:27021','mongodb-${COLOR_PREFIX}1:27021','mongodb-${COLOR_PREFIX}2:27021','mongodb-${COLOR_PREFIX}3:27021'\]/g" $FAWKES_DIR/cfg/conf.d/robot-memory.yaml
+sed -i "s/hosts:/hosts:\n        mongodb-planner-${TEAM_COLOR,,}: mongodb-planner-${TEAM_COLOR,,}:27021/g" $FAWKES_DIR/cfg/conf.d/robot-memory.yaml
 sed -i "/plugins\/mongodb\/clients/,+50d" $FAWKES_DIR/cfg/gazsim-configurations/gazsim-config-override.yaml
 
 sed -i "s/GOALORDER|{relation:'order'/GOALORDER|{relation:'order',id:1/g" $FAWKES_DIR/src/agents/rcll-pddl/pddl-problem-template.pddl
 sed -i "s/GOALORDER|{relation:'order'/GOALORDER|{relation:'order',id:1/g" $FAWKES_DIR/src/agents/rcll-pddl/pddl-problem-template-cyan.pddl
 sed -i "s/GOALORDER|{relation:'order'/GOALORDER|{relation:'order',id:1/g" $FAWKES_DIR/src/agents/rcll-pddl/pddl-problem-template-magenta.pddl
 
+echo "Waiting for MongoDB"
+MAX_TRIES=${REFBOX_MONGODB_WAIT_MAX_TRIES:-50}
+PERIOD=${REFBOX_MONGODB_WAIT_PERIOD:-1}
+for h in "mongodb-planner-${TEAM_COLOR,,}" "mongodb-${COLOR_PREFIX}1" "mongodb-${COLOR_PREFIX}2" "mongodb-${COLOR_PREFIX}3"; do
+  TRIES=0
+  REFBOX_MONGODB_HOST=$h
+  REFBOX_MONGODB_PORT=27021
+  while ! curl -f -s "http://$REFBOX_MONGODB_HOST:$REFBOX_MONGODB_PORT" >/dev/null; do
+    (( TRIES=TRIES+1 ))
+    if (( $TRIES >= $MAX_TRIES )); then
+      >&2 echo "Could not reach MongoDB $h after $TRIES tries, giving up"
+      exit 21
+    else
+      sleep $PERIOD
+    fi
+  done
+  (( TRIES=TRIES+1 ))
+  echo "MongoDB $h reachable after $TRIES/$MAX_TRIES tries"
+done
 
 $FAWKES_DIR/bin/fawkes -c $CONF -L console -l $LL $META_PLUGIN || exit 42
